# Generated by Django 4.1.4 on 2022-12-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_url', models.CharField(max_length=100)),
                ('avg_prep_time', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_api.location')),
            ],
        ),
        migrations.CreateModel(
            name='StoreEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='store_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='OpenTimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('holiday_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_time_periods', to='store_api.holiday')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_dates', to='store_api.store'),
        ),
    ]
