# Generated by Django 4.1.4 on 2022-12-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store_api.location'),
        ),
    ]
