# Generated by Django 4.1.4 on 2023-01-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store_api.location'),
        ),
    ]
