# Generated by Django 4.1.4 on 2023-02-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_config', to='store_api.store')),
            ],
            options={
                'verbose_name': 'Menu Configuration',
                'verbose_name_plural': 'Menu Configurations',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('categories', models.ManyToManyField(blank=True, related_name='menus', to='menu_api.category')),
                ('menu_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu_api.menuconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(blank=True, max_length=300)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.menu')),
                ('menu_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.menuconfig')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu_api.menuconfig'),
        ),
    ]
