# Generated by Django 4.1.4 on 2023-01-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(to='menu_api.category'),
        ),
    ]
