# Generated by Django 4.1.4 on 2023-01-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0002_alter_menu_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuconfig',
            options={'verbose_name': 'Menu Configuration', 'verbose_name_plural': 'Menu Configurations'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='categories',
        ),
    ]
