# Generated by Django 4.1.4 on 2023-01-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0003_alter_category_options_alter_menuconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('image_url', models.URLField(max_length=300)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.menu')),
                ('menu_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.menuconfig')),
            ],
        ),
    ]
