# Generated by Django 4.1.4 on 2023-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
