# Generated by Django 4.1.4 on 2023-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0005_alter_item_image_url_alter_item_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, to='menu_api.category'),
        ),
    ]
