# Generated by Django 4.1.4 on 2023-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0006_menu_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menu_api.category'),
        ),
    ]
